### ISSUE TITLE
Hey.. Looked at your code. 

### ISSUE THREAD

**Issue by petterek** [michalxsekula/StockExchangeHelper#1]
This looks good. If you want some advice from me I would recomend to split the soulution into 2 projects and put the implementation of the business logic there. 

Also you should use the dependency injection capabilities in MVC to avoid the hard coupeling in the usage of the service. 

Apart from that it looks good I think :) 

PEtter @Simployertech polska

**Comment by michalxsekula** [comment]
Thank you for your code review. I haven't noticed it before, however I added dependency injection anyway :) And thanks for advice on splitting code for two projects, I will try to apply this.

[Update 20.02.2018] :  I tried to separate business logic from mvc model. I have also wrapped loggers into interfaces, and provide loggerManager. Concrete implementations of loggers are injected by unity container.  The following changes are on CreateBusinessLayer branch : )
